language: erlang

env:
  global:
    - PLATFORM=linux
    - LUAROCKS_VER=2.2.0beta1
  matrix:
    - LUA=lua5.1
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh

script: "tests/tests.lua 30logclasscommons_test"

notifications:
  email:
    on_success: change
    on_failure: always
